PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_/CTDI/REP_RESULT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD /CTDI/REP_RESULT-VBELN .
    FIELD /CTDI/REP_RESULT-BEMOT .
    FIELD /CTDI/REP_RESULT-AKZ .
    FIELD /CTDI/REP_RESULT-TAUSCHFALL .
    FIELD /CTDI/REP_RESULT-REPRES_TXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD /CTDI/REP_RESULT-VBELN .
    FIELD /CTDI/REP_RESULT-BEMOT .
    FIELD /CTDI/REP_RESULT-AKZ .
    FIELD /CTDI/REP_RESULT-TAUSCHFALL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
